### ISSUE TITLE
Update modules to use markups instead of annotations

### ISSUE THREAD

**Issue by lassoan** [fedorov/ChangeTrackerPy#18]
Annotations module, which provides `vtkMRMLAnnotationROI` and `vtkMRMLAnnotationRuler` nodes have been deprecated since April 2021 and will be removed in Slicer-5.4 stable version early next year.
Since some modules in this extension use annotation nodes, these modules need to be updated to use markups nodes before the end of this year.

[This section](https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide/Slicer#Slicer_5.3%3A_Removed_Annotation_module) of the migration guide should help with implementing the changes and any questions can be asked at the [Remove Annotations module topic in the Slicer forum](https://discourse.slicer.org/t/remove-annotations-module/25271).

Impacted module: ChangeTracker\ChangeTrackerWizard\ChangeTrackerDefineROIStep.py

**Comment by fedorov** [comment]
There are no resources to maintain this extension, and I am not sure anyone is using it.

I suggest deprecating the module and removing it from the Extensions index, and direct users to the older version of Slicer if someone wants to use it.

**Comment by lassoan** [comment]
I went ahead and updated the module (see https://github.com/fedorov/ChangeTrackerPy/pull/19), just a few small changes were needed. Self-test passes, too.
